# Start Homebrew Releaser when a new tag is created
on:
  push:
    tags:
      - "*"

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: j5pu
          homebrew_tap: homebrew-tools
          formula_folder: Formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: j5pu
          commit_email: homebrew-releaser@example.com
          install: 'bin.install "src/my-script.sh" => "my-script"'
          test: 'assert_match("my script output", shell_output("my-script-command"))'
          skip_commit: false
          update_readme_table: true
          debug: false
